# This file is in YAML format
# Declared variables to be passed into $/templates files

namespace: phoenix-prod

image:
  repository: 988207228673.dkr.ecr.eu-central-1.amazonaws.com/phoenix-contents-api
  tag: prod
  pullPolicy: Always

imagePullSecrets: []

service:
  type: NodePort
  port: 80

ingress:
  external:
    sslRedirect: "false"
    forceSslRedirect: "false"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 85

dns:
  internal: prod.sgp.private.wiley.host
  external: prod.sgp.wiley.host

env_vars:
  data:
    KAFKA_HOST: b-1.eksprodeu.5cp134.c8.kafka.eu-central-1.amazonaws.com:9092,b-2.eksprodeu.5cp134.c8.kafka.eu-central-1.amazonaws.com:9092
    KAFKA_TOPIC: ck-phoenix-trainingProgram
    LOG_JSON: "true"
    LOG_MINIMUMLEVEL: Information
    MONGO_DB_NAME: contents-api
    MONGO_TLS_CA_FILE_PATH: "/cert/global-bundle.pem"
    KEYCLOAK_BASE_URL: "https://keycloak.prod.sgp.wiley.host"
    KEYCLOAK_REALM: "phoenix"
    KEYCLOAK_AUDIENCE: "account"
    OPA_BASE_URL: "http://opa"
    GATEWAY_HOST: "phoenix.prod.sgp.wiley.host"

externalsecrets:
  refreshInterval: 1m
  secretCreationPolicy: Owner
  secretStoreName: eks-prod-eu-secret-manager
  secretStoreType: ClusterSecretStore
  data:
  - keyValue: eks/phoenix
    nameValue: API_KEY
    propertyValue: CONTENTS_API_KEY
  - keyValue: eks/phoenix
    nameValue: MONGO_CONNECTION_STRING
    propertyValue: CONTENTS_API_PROD_MONGO_CONNECTION_STRING
