# This file is in YAML format
# Declared variables to be passed into $/templates files

appName: contents-api

imagePullSecrets: []

service:
  type: NodePort
  port: 80
  targetPort: 80

ingress:
  external:
    sslRedirect: "false"
    forceSslRedirect: "true"

# replicacount has no impact if autoscaling.enabled = true
replicacount: 1
autoscaling:
  enabled: false